import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :wortwildnis, WortwildnisWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# also known as HSTS. `:force_ssl` is required to be set at compile-time.
# config :wortwildnis, WortwildnisWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]
config :wortwildnis, WortwildnisWeb.Endpoint,
  url: [host: "wortwildnis-dev.jan-wirth.de", scheme: "https", port: 443],
  # force_ssl: [rewrite_on: [x_forwarded_proto: "https"]],
  # force_ssl: [x_forwarded_proto: "https"],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  http: [ip: {0, 0, 0, 0}, port: 4000]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
