defmodule Wortwildnis.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:terms, [:owner_id])

    create index(:terms, ["lower(name)"], name: "terms_lower_name_index")

    create index(:reactions, [:term_id])
  end

  def down do
    drop_if_exists index(:reactions, [:term_id])

    drop_if_exists index(:terms, ["lower(name)"], name: "terms_lower_name_index")

    drop_if_exists index(:terms, [:owner_id])
  end
end
