defmodule Wortwildnis.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:term_contained_terms, [:contained_term_id])

    drop_if_exists index(:term_contained_terms, [:term_id])
  end

  def down do
    create index(:term_contained_terms, [:term_id])

    create index(:term_contained_terms, [:contained_term_id])
  end
end
