defmodule Wortwildnis.Repo.Migrations.AddUsernameToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add username as nullable first
    alter table(:users) do
      add :username, :text, null: true
    end

    # Set default username for existing user
    execute(
      "UPDATE users SET username = 'jannibeu' WHERE id = '2dbc514e-1fd3-4a1d-b905-beaf2dc63fc6'"
    )

    # Make username non-nullable
    alter table(:users) do
      modify :username, :text, null: false
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :username
    end
  end
end
