defmodule Wortwildnis.Repo.Migrations.AddScrapedFromMundmische do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, default: "user"
    end

    alter table(:terms) do
      add :translation_en, :text
      add :scraped_from_mundmische, :boolean, null: false, default: false

      add :owner_id,
          references(:users,
            column: :id,
            name: "terms_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reaction_type, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "reactions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :term_id,
          references(:terms,
            column: :id,
            name: "reactions_term_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:reactions, [:user_id, :term_id, :reaction_type],
             name: "reactions_unique_reaction_index"
           )
  end

  def down do
    drop_if_exists unique_index(:reactions, [:user_id, :term_id, :reaction_type],
                     name: "reactions_unique_reaction_index"
                   )

    drop constraint(:reactions, "reactions_user_id_fkey")

    drop constraint(:reactions, "reactions_term_id_fkey")

    drop table(:reactions)

    drop constraint(:terms, "terms_owner_id_fkey")

    alter table(:terms) do
      remove :owner_id
      remove :scraped_from_mundmische
      remove :translation_en
    end

    alter table(:users) do
      remove :role
    end
  end
end
