defmodule Wortwildnis.Repo.Migrations.AddTermOfTheDay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:users) do
    #   add :term_draft, :map
    # end

    alter table(:terms) do
      add :term_of_the_day, :date
    end

    create unique_index(:terms, [:term_of_the_day],
             name: "terms_unique_term_of_the_day_index",
             where: "(term_of_the_day IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:terms, [:term_of_the_day],
                     name: "terms_unique_term_of_the_day_index"
                   )

    alter table(:terms) do
      remove :term_of_the_day
    end

    alter table(:users) do
      remove :term_draft
    end
  end
end
