defmodule Wortwildnis.Repo.Migrations.NameDescriptionUniqueIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:terms) do
    #   # add :translation_es, :text
    #   # add :example, :text
    # end

    create unique_index(:terms, [:name, :description],
             name: "terms_unique_name_description_index"
           )
  end

  def down do
    drop_if_exists unique_index(:terms, [:name, :description],
                     name: "terms_unique_name_description_index"
                   )

    # alter table(:terms) do
    #   # remove :example
    #   # remove :translation_es
    # end
  end
end
