defmodule Wortwildnis.Repo.Migrations.AddContainedTermsCache do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terms) do
      add :contained_terms_cache, {:array, :map}
    end
  end

  def down do
    alter table(:terms) do
      remove :contained_terms_cache
    end
  end
end
