defmodule Wortwildnis.Repo.Migrations.AddSearchTrgmIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:terms, ["name gin_trgm_ops"], name: "terms_name_trgm_index", using: "gin")
  end

  def down do
    drop_if_exists index(:terms, ["name gin_trgm_ops"], name: "terms_name_trgm_index")
  end
end
